version: '2'

services:
  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ${DB_HOST_MOUNT}:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=sun6urn31
    env_file:
      - db.env

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: always

  app:
    container_name: nextcloud-app
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ${APP_HOST_MOUNT}:/var/www/html
      - ${EXT_DATA_HOST_ACCESS}:/srv
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  collabora:
    image: collabora/code
    restart: always
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - domain=${NC_DOMAIN}
      - VIRTUAL_HOST=${COLLAB_DOMAIN}
      - VIRTUAL_NETWORK=proxy-tier
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=${COLLAB_DOMAIN}
      - LETSENCRYPT_EMAIL=admin@noan.me
    networks:
      - proxy-tier

  web:
    container_name: nextcloud-web
    build: ./web
    restart: always
    volumes:
      - ${APP_HOST_MOUNT}:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=${NC_DOMAIN}
      - LETSENCRYPT_HOST=${NC_DOMAIN}
      - LETSENCRYPT_EMAIL=admin@noan.me
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    container_name: nextcloud-cron
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ${APP_HOST_MOUNT}:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

networks:
  proxy-tier:
    external:
      name: proxy-ssl
